# Chapter 1: Data Manipulation

In [3]:
import torch

In [2]:
torch.cuda.is_available()

True

## 1. What is a Tensor?

- scaler = number 
- vector = 1-dimensional array
- matrix = 2-dimensional array
- tensors = n-dimensional arrays

## 2. Advantages of a Tensor?

- supports automation differentiation
- leverages GPUs to accelerate numerical computation (numpy only runs on CPU)

##  3. Propoerties of Tensor

### Arange

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

### Inspect total number of elements

In [5]:
x.numel()

12

### Access tensor's shape

In [6]:
x.shape

torch.Size([12])

### Change shape of tensor

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Not necessary to specify every shape component because we already know the tensor size. To automatically infer one component of the shape, can place a -1 for the shape component that is to be inferred automatically

In [8]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### Zeros tensor

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### Ones tensor

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Create random samples from a given probability distribution

In [11]:
torch.randn(3, 4)

tensor([[-0.1117, -0.9452, -0.2364,  1.4661],
        [-0.5051,  0.3760,  1.4026, -0.1464],
        [ 0.6416, -2.8266,  0.8467, -0.9768]])

### Create tensor manually

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 4. Indexing and Slicing

In [13]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

When only one index is specified, it is applied along axis 0.

In [14]:
# Last row
X[-1]

tensor([ 8.,  9., 10., 11.])

In [15]:
# Row 1 to 2
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Assign multiple elements the same value

In [18]:
# Access the rows up to 2, then take all elements along columns.
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 5. Operations

In [19]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

### Element wise operations
- Applies to all elements of a tensor

In [20]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [22]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [23]:
# Addition
x + y

tensor([ 3.,  4.,  6., 10.])

In [24]:
# Subtraction
x - y

tensor([-1.,  0.,  2.,  6.])

In [25]:
# Multiplication
x * y

tensor([ 2.,  4.,  8., 16.])

In [26]:
# Division
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [28]:
# Exponentiation
x ** y

tensor([ 1.,  4., 16., 64.])

### Concatenate Tensors

In [34]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [33]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [30]:
# row wise
torch.cat((X, Y), dim=0) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [37]:
# column wise
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

### Logical Statements

In [38]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

### Summing all elements

In [39]:
X.sum()

tensor(66.)

## 6. Broadcasting

Even when shape differ, we can still perform elementwise binary operations through broadcasting mechanism.
- Expand one or both arrays by copying elements along axes with length 1 so that after transformation the two tensors have same shape
- perform elementwise operation on the resulting arrays

In [43]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

In [44]:
# 3 x 1
a

tensor([[0],
        [1],
        [2]])

In [45]:
# 1 x 2
b

tensor([[0, 1]])

In [46]:
# make 'a' have 2 columns (replicate)
# make 'b' have 3 rows (replicate)
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 7. Saving Memory

When we perform operation like ``Y = X + Y``, new memory is allocation to the host result. We can dereference the old Y and instead point the new Y to the newly allocated memory. We do not want to run around allocating memory unnecessarily. We want to perform in-place operations

In [48]:
before = id(Y)
before

2041204363568

In [49]:
Y = Y + X
id(Y)

2041342605968

In [50]:
# overwrite values of tensor Z using :
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

id(Z): 2041342366720


In [51]:
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2041342366720


## 8. Conversion to Other Python Objects

### Converting from numpy to torch

In [53]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

### Converting a size-1 tensor to scalar

In [54]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [55]:
a.item()

3.5

In [56]:
float(a)

3.5

In [57]:
int(a)

3